image: maven:3.6.3-amazoncorretto-11

stages:
  - build
  - release
  
before_script:  
  - PATH="${PATH}:${M2_HOME}/bin"

job build_only:
  stage: build
  tags:
    - mvn-conf
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/mobile-banking-service-1.0.0.jar
     


      
job build_with_dockerimage:
  stage: release
  tags:
    - mvn-conf
  script:
    - if [[ ${SKIP_RELEASE} == "Y" ]] || [[ ${SKIP_RELEASE} == "y" ]]  ; then echo "Image creation is skipped " ;exit 0 ;else echo "Running the release job for Image creation. " ; fi;
    - mvn --non-recursive help:evaluate -Dexpression=project.version | grep -v '\[.*'
    - TAG=$(mvn --non-recursive help:evaluate -Dexpression=project.version | grep -v '\[.*') 
    - SERVICE_NAME=$(mvn --non-recursive help:evaluate -Dexpression=project.artifactId | grep -v '\[.*') 
    - COMPLETE_IMAGE=$DOCKER_REPO/$DOCKER_PROJECT/$SERVICE_NAME:$TAG
    - echo $COMPLETE_IMAGE
    - if [$(docker pull $COMPLETE_IMAGE >> /tmp/dockerpull_output.txt 2> /tmp/dockerpull_output.txt)]; then echo " docker pull completed "  ;fi
    - cat /tmp/dockerpull_output.txt
    - OUTPUT=$(cat  /tmp/dockerpull_output.txt)
    - rm /tmp/dockerpull_output.txt
    - if echo $OUTPUT | grep -q "Downloaded newer image" || echo $OUTPUT | grep -q "Image is up to date"; then echo "Image already existing. Please update the project version and retry!" ; docker image rm $COMPLETE_IMAGE ; exit 1; else echo "Pipeline seems good to proceed with docker image creation."; fi;
    - mvn -Dmvn_user=$MAVEN_USER -Dmvn_pwd=$MAVEN_PASSWORD clean install -Dmaven.test.skip=true -Dpmd.skip=true -Dfindbugs.skip=true -Denforcer.skip=true -Dfmt.skip=true -Dassembly.skipAssembly=true
  only:
    - web
