openapi: 3.0.1
info:
  title: Mobile Banking API
  description: This is a sample API used to illustrate the tooling around an API-first approach.
  version: 1.0.0
servers:
  - url: 'http://localhost:9096'
    description: dev
paths:
  /accounts:
    get:
      summary: Retrieve all accounts.
      operationId: getAccounts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountsResponse'
components:
  schemas:
    Account:
      type: object
      required:
        - iban
      properties:
        iban:
          type: string
    GetAccountsResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Account'